### ISSUE TITLE
案内文を作る

### ISSUE THREAD

**Issue by rindrics** [kikirinrin/shell2cd#24]
目的や対象者を明記せよ

**Comment by akimanabe** [comment]
時間割、目的、対象者、対象にならない人、キーワード

**Comment by akimanabe** [comment]
具体的には？

- GitHubのページは使ってるけど、Zipで落としてばかりの人。
- GitHubにあるよ、と言われるけどよくわからない人。
- Issue投げてくださいって何？
- コマンドとか暗記しないといけないの？

**Comment by rindrics** [comment]
https://github.com/fra-dev-ops-bu/text_github でだいぶ解決された
